### ISSUE TITLE
vite_ruby is incompatible with derailed_benchmarks gem

### ISSUE THREAD

**Issue by CyberAP** [ElMassimo/vite_ruby#239]
[troubleshooting section]: https://vite-ruby.netlify.app/guide/troubleshooting.html

- [x] I have tried upgrading by running `bundle update vite_ruby`.
- [x] I have read the __[troubleshooting section]__ before opening an issue.

### Description 📖

If you install `vite_ruby` in a Rails 6.1 project that has a `derailed_benchmarks` gem you'll get an error that says:

```
bundler: failed to load command: derailed (/builds/gitlab-org/gitlab/vendor/ruby/2.7.0/bin/derailed)
/builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/callbacks.rb:25:in `on_file_autoloaded': expected file /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/vite_ruby-3.2.0/lib/vite_ruby.rb to define constant ViteRuby, but didn't (Zeitwerk::NameError)
```

### Reproduction 🐞

1. Install `rails ~> 6.1.6.1`
2. Install `derailed_benchmarks`
3. Instal `vite_ruby`
4. Run `bundle exec derailed exec perf:mem`

Or you can try to reproduce it using [GDK](https://gitlab.com/gitlab-org/gitlab-development-kit): https://gitlab.com/gitlab-org/gitlab/-/merge_requests/94685

<details>
<summary>Vite Ruby Info</summary>

_Run `bin/rake vite:info` and provide the output:_

```
bin/vite present?: true
vite_ruby: 3.2.0
vite_rails: 3.0.10
rails: 6.1.6.1
node: v14.18.3
npm: 6.14.15
yarn: 1.22.17
pnpm: 
ruby: ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [arm64-darwin21]

installed packages:
/Users/stas/projects/gitlab-development-kit/gitlab
├── vite@3.0.4 
└── vite-plugin-ruby@3.1.2 
```
</details>

### Logs 📜

_If not providing a reproduction:_

<details>
<summary>Output</summary>

```
bundler: failed to load command: derailed (/builds/gitlab-org/gitlab/vendor/ruby/2.7.0/bin/derailed)
/builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/callbacks.rb:25:in `on_file_autoloaded': expected file /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/vite_ruby-3.2.0/lib/vite_ruby.rb to define constant ViteRuby, but didn't (Zeitwerk::NameError)
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:28:in `require'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/derailed_benchmarks-2.1.1/lib/derailed_benchmarks/core_ext/kernel_require.rb:86:in `require'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/vite_ruby-3.2.0/lib/vite_ruby/version.rb:3:in `<top (required)>'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/dead_end-3.1.1/lib/dead_end/core_ext.rb:19:in `require'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/dead_end-3.1.1/lib/dead_end/core_ext.rb:19:in `require'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/derailed_benchmarks-2.1.1/lib/derailed_benchmarks/core_ext/kernel_require.rb:30:in `block in require'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/derailed_benchmarks-2.1.1/lib/derailed_benchmarks/core_ext/kernel_require.rb:65:in `measure_memory_impact'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/derailed_benchmarks-2.1.1/lib/derailed_benchmarks/core_ext/kernel_require.rb:29:in `require'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/derailed_benchmarks-2.1.1/lib/derailed_benchmarks/core_ext/kernel_require.rb:86:in `require'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/vite_ruby-3.2.0/lib/vite_ruby.rb:18:in `<top (required)>'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/dead_end-3.1.1/lib/dead_end/core_ext.rb:19:in `require'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/dead_end-3.1.1/lib/dead_end/core_ext.rb:19:in `require'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/derailed_benchmarks-2.1.1/lib/derailed_benchmarks/core_ext/kernel_require.rb:30:in `block in require'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/derailed_benchmarks-2.1.1/lib/derailed_benchmarks/core_ext/kernel_require.rb:65:in `measure_memory_impact'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/derailed_benchmarks-2.1.1/lib/derailed_benchmarks/core_ext/kernel_require.rb:29:in `require'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/derailed_benchmarks-2.1.1/lib/derailed_benchmarks/core_ext/kernel_require.rb:86:in `require'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/vite_rails-3.0.10/lib/vite_rails.rb:3:in `<top (required)>'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/dead_end-3.1.1/lib/dead_end/core_ext.rb:19:in `require'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/dead_end-3.1.1/lib/dead_end/core_ext.rb:19:in `require'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/derailed_benchmarks-2.1.1/lib/derailed_benchmarks/core_ext/kernel_require.rb:30:in `block in require'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/derailed_benchmarks-2.1.1/lib/derailed_benchmarks/core_ext/kernel_require.rb:65:in `measure_memory_impact'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/derailed_benchmarks-2.1.1/lib/derailed_benchmarks/core_ext/kernel_require.rb:29:in `require'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/runtime.rb:55:in `each'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/runtime.rb:55:in `block in require'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/runtime.rb:44:in `each'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/runtime.rb:44:in `require'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler.rb:187:in `require'
	from /builds/gitlab-org/gitlab/config/application.rb:15:in `<top (required)>'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/dead_end-3.1.1/lib/dead_end/core_ext.rb:19:in `require'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/dead_end-3.1.1/lib/dead_end/core_ext.rb:19:in `require'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/derailed_benchmarks-2.1.1/lib/derailed_benchmarks/core_ext/kernel_require.rb:30:in `block in require'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/derailed_benchmarks-2.1.1/lib/derailed_benchmarks/core_ext/kernel_require.rb:65:in `measure_memory_impact'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/derailed_benchmarks-2.1.1/lib/derailed_benchmarks/core_ext/kernel_require.rb:29:in `require'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/derailed_benchmarks-2.1.1/lib/derailed_benchmarks/core_ext/kernel_require.rb:86:in `require'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/derailed_benchmarks-2.1.1/lib/derailed_benchmarks/load_tasks.rb:21:in `block (2 levels) in <top (required)>'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/derailed_benchmarks-2.1.1/lib/derailed_benchmarks/load_tasks.rb:69:in `block (2 levels) in <top (required)>'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/derailed_benchmarks-2.1.1/bin/derailed:45:in `exec'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/gems/derailed_benchmarks-2.1.1/bin/derailed:96:in `<top (required)>'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/bin/derailed:25:in `load'
	from /builds/gitlab-org/gitlab/vendor/ruby/2.7.0/bin/derailed:25:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/cli/exec.rb:58:in `load'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/cli/exec.rb:23:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/cli.rb:483:in `exec'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/cli.rb:31:in `dispatch'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/cli.rb:25:in `start'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/exe/bundle:48:in `block in <top (required)>'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/friendly_errors.rb:[117](https://gitlab.com/gitlab-org/gitlab/-/jobs/2846106978#L117):in `with_friendly_errors'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/exe/bundle:36:in `<top (required)>'
	from /usr/local/bin/bundle:23:in `load'
	from /usr/local/bin/bundle:23:in `<main>'
```
</details>

**Comment by ElMassimo** [comment]
The way the loader is used in Vite Ruby follows the [recommended approach](https://github.com/fxn/zeitwerk#for_gem) in Zeitwerk.

> it is important that the setup call happens above the main module definition

I'd recommend that you ask in `derailed_benchmarks` to see if they are aware of this type of issue, as it seems related to the assumption that the constant would be already defined when `setup` is called, which is the opposite of what Zeitwerk recommends.

Closing as this doesn't seem actionable on my end at the moment, but happy to make any changes if the setup here is incorrect.

**Comment by ElMassimo** [comment]
After looking at this, I think `derailed_benchmarks` is forcing the load in a way that seems to be more strict than what the default Rails eager loading process does.

I've released [this change](https://github.com/ElMassimo/vite_ruby/commit/7b920627f0f551166b3ab321e50b6cee746168c2), which should prevent that incompatibility.

**Comment by CyberAP** [comment]
You're a hero, @ElMassimo! Thank you!
