### ISSUE TITLE
Unexpected reserved word (Bug)

### ISSUE THREAD

**Issue by chmich** [ElMassimo/vite_ruby#250]
Hi, followed the steps

`rails new my-app`
add the gem, bundle install and `bundle exec vite:install`
and then tried to start the server `bin/vite dev` receipted the error:

```
MacBook: ~/playground/rails7-vite-bootstrap$ bin/vite dev
file:///Users/dev/playground/rails7-vite-bootstrap/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
    at async link (internal/modules/esm/module_job.js:42:21)
MacBook: ~/playground/rails7-vite-bootstrap$ 

```

**Comment by ElMassimo** [comment]
Hi Christian!

Please [follow the installation instructions](https://vite-ruby.netlify.app/guide/#setup-%F0%9F%93%A6).

> bundle exec vite:install

Unless you have a typo in the bug report, the correct command is:

```
bundle exec vite install
```

As mentioned in the [installation instructions](https://vite-ruby.netlify.app/guide/#setup-%F0%9F%93%A6), this will create a `bin/vite` file in your project. The error you are seeing suggests that this file has not been created.

**Comment by chmich** [comment]
Thanks, 
ElMassimo, for the fast response.
And yes, that command i wrote wrong, but it makes no difference, once again:

1. `rails new vite` #=> rails 7.0.3 / ruby 3.1.2
2. added `gem "vite_rails"` to Gemfile
3. see terminal:
 
```
MacBook: ~/playground/vite$ bundle exec vite install
Creating binstub
Check that your vite.json configuration file is available in the load path:

	No such file or directory @ rb_sysopen - /Users/dev/playground/vite/config/vite.json

Creating configuration files
Installing sample files
Installing js dependencies

added 36 packages, and audited 37 packages in 3s

7 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Adding files to .gitignore

Vite ⚡️ Ruby successfully installed! 🎉
MacBook: ~/playground/vite$ bin/vite dev
file:///Users/dev/playground/vite/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
    at async link (internal/modules/esm/module_job.js:42:21)
MacBook: ~/playground/vite$ 
```

**Comment by chmich** [comment]
Now he tells me more:

```
MacBook: ~/playground/vite-bootstrap$ bundle exec vite dev
/Users/dev/.rvm/gems/ruby-3.1.2/gems/vite_ruby-3.2.3/lib/vite_ruby/runner.rb:19:in `rescue in run': ❌ The vite binary is not available. Have you installed the npm packages? (ViteRuby::MissingExecutableError)

Visit the Troubleshooting guide for more information:
  https://vite-ruby.netlify.app/guide/troubleshooting.html#troubleshooting

No such file or directory - /Users/dev/playground/vite-bootstrap/node_modules/.bin/vite
        from /Users/dev/.rvm/gems/ruby-3.1.2/gems/vite_ruby-3.2.3/lib/vite_ruby/runner.rb:10:in `run'
        from /Users/dev/.rvm/gems/ruby-3.1.2/gems/vite_ruby-3.2.3/lib/vite_ruby.rb:115:in `run'
        from /Users/dev/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/forwardable.rb:238:in `run'
        from /Users/dev/.rvm/gems/ruby-3.1.2/gems/vite_ruby-3.2.3/lib/vite_ruby/cli/dev.rb:11:in `block in call'
        from /Users/dev/.rvm/gems/ruby-3.1.2/gems/vite_ruby-3.2.3/lib/vite_ruby/cli/vite.rb:22:in `call'
        from /Users/dev/.rvm/gems/ruby-3.1.2/gems/vite_ruby-3.2.3/lib/vite_ruby/cli/dev.rb:11:in `call'
        from /Users/dev/.rvm/gems/ruby-3.1.2/gems/dry-cli-0.7.0/lib/dry/cli.rb:116:in `perform_registry'
        from /Users/dev/.rvm/gems/ruby-3.1.2/gems/dry-cli-0.7.0/lib/dry/cli.rb:65:in `call'
        from /Users/dev/.rvm/gems/ruby-3.1.2/gems/vite_ruby-3.2.3/exe/vite:12:in `<top (required)>'
        from /Users/dev/.rvm/gems/ruby-3.1.2/bin/vite:25:in `load'
        from /Users/dev/.rvm/gems/ruby-3.1.2/bin/vite:25:in `<main>'
        from /Users/dev/.rvm/gems/ruby-3.1.2/bin/ruby_executable_hooks:22:in `eval'
        from /Users/dev/.rvm/gems/ruby-3.1.2/bin/ruby_executable_hooks:22:in `<main>'
/Users/dev/.rvm/gems/ruby-3.1.2/gems/vite_ruby-3.2.3/lib/vite_ruby/runner.rb:13:in `exec': No such file or directory - /Users/dev/playground/vite-bootstrap/node_modules/.bin/vite (Errno::ENOENT)
        from /Users/dev/.rvm/gems/ruby-3.1.2/gems/vite_ruby-3.2.3/lib/vite_ruby/runner.rb:13:in `block in run'
        from /Users/dev/.rvm/gems/ruby-3.1.2/gems/vite_ruby-3.2.3/lib/vite_ruby/runner.rb:11:in `chdir'
        from /Users/dev/.rvm/gems/ruby-3.1.2/gems/vite_ruby-3.2.3/lib/vite_ruby/runner.rb:11:in `run'
        from /Users/dev/.rvm/gems/ruby-3.1.2/gems/vite_ruby-3.2.3/lib/vite_ruby.rb:115:in `run'
        from /Users/dev/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/forwardable.rb:238:in `run'
        from /Users/dev/.rvm/gems/ruby-3.1.2/gems/vite_ruby-3.2.3/lib/vite_ruby/cli/dev.rb:11:in `block in call'
        from /Users/dev/.rvm/gems/ruby-3.1.2/gems/vite_ruby-3.2.3/lib/vite_ruby/cli/vite.rb:22:in `call'
        from /Users/dev/.rvm/gems/ruby-3.1.2/gems/vite_ruby-3.2.3/lib/vite_ruby/cli/dev.rb:11:in `call'
        from /Users/dev/.rvm/gems/ruby-3.1.2/gems/dry-cli-0.7.0/lib/dry/cli.rb:116:in `perform_registry'
        from /Users/dev/.rvm/gems/ruby-3.1.2/gems/dry-cli-0.7.0/lib/dry/cli.rb:65:in `call'
        from /Users/dev/.rvm/gems/ruby-3.1.2/gems/vite_ruby-3.2.3/exe/vite:12:in `<top (required)>'
        from /Users/dev/.rvm/gems/ruby-3.1.2/bin/vite:25:in `load'
        from /Users/dev/.rvm/gems/ruby-3.1.2/bin/vite:25:in `<main>'
        from /Users/dev/.rvm/gems/ruby-3.1.2/bin/ruby_executable_hooks:22:in `eval'
        from /Users/dev/.rvm/gems/ruby-3.1.2/bin/ruby_executable_hooks:22:in `<main>'
MacBook: ~/playground/vite-bootstrap$ 

```

i did a additional `yarn install` but makes no difference

**Comment by chmich** [comment]
it is just missing the file `/node_modules/.bin/vite`

**Comment by chmich** [comment]
By creating the new app with `rails new my-app --skip-javascript` and then adding vite and running the generator is creates the `/node_modules/.bin/vite` file and, then, it also creates the `app/frontend` folder. So, now i can run the development server. But HMR is not working yet.

**Comment by chmich** [comment]
That was it!
Now my app runs fine, including HMR.
Thanks for this Gem.
The best is to create the app with `rails new --skip-javascript --skip-asset-pipeline` for avoiding conflicts and using then the `vite_stylesheet_tag` too. 
i would suggest add this to docu.
