### ISSUE TITLE
unexpected token {

### ISSUE THREAD

**Issue by wdiechmann** [ElMassimo/vite_ruby#286]
[troubleshooting section]: https://vite-ruby.netlify.app/guide/troubleshooting.html

- [x] I have tried upgrading by running `bundle update vite_ruby`.
- [x] I have read the __[troubleshooting section]__ before opening an issue.

### Description 📖

Doing a fresh Rails install and following up with installing **vite** leaves me with this output

```
√ vite % bundle exec bin/vite dev
/Users/walther/Deling/Walther/src/testing/vite/node_modules/vite/bin/vite.js:2
import { performance } from 'node:perf_hooks'
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:872:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11

```

### Reproduction 🐞

I did this

```
rails new vite
cd vite
bundle add vite_rails
bundle exec vite install
bin/vite dev
```

<details>
<summary>Vite Ruby Info</summary>

```
bin/vite present?: true
vite_ruby: 3.2.7
vite_rails: 3.0.12
rails: 7.0.4
node: v12.10.0
npm: 6.10.3
yarn: 1.22.19
pnpm: 
ruby: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]

installed packages:
/Users/walther/Deling/Walther/src/testing/vite
├── vite@3.1.8 
└── vite-plugin-ruby@3.1.2 
```
</details>

### Logs 📜

_If not providing a reproduction:_

<details>
<summary>Output</summary>

_Run `DEBUG=vite-plugin-ruby:* bin/vite dev` or `DEBUG=vite-plugin-ruby:* bin/vite build` and provide the output:_

```
vite % DEBUG=vite-plugin-ruby:* bin/vite build 
Building with Vite ⚡️
/Users/walther/Deling/Walther/src/testing/vite/node_modules/vite/bin/vite.js:2
import { performance } from 'node:perf_hooks'
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:872:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11

Build with Vite failed! ❌
?1 vite % 
```
</details>

### Screenshots 📷

_Provide console or browser screenshots of the problem_.

**Comment by wdiechmann** [comment]
😮 

vite does not use importmap to pin javascripts - I just realized!!

that immediately begs the question why (wanting to get rid of the npm/yarn dependency) 

but I did manage to be on my way doing a simple `yarn install`

😄
