### ISSUE TITLE
Running bin/vite fails on production with bundler

### ISSUE THREAD

**Issue by omsoft** [ElMassimo/vite_ruby#348]
I'm using vite_rails (3.0.14) with  vite_ruby (3.3.0), and running `bin/vite` results in this error from bundler:

```
Activating bundler (< 2) failed:
Could not find 'bundler' (< 2) - did find: [bundler-2.3.7,bundler-2.2.11]
Checked in 'GEM_PATH=/usr/share/rvm/gems/ruby-3.1.1:/usr/share/rvm/rubies/ruby-3.1.1/lib/ruby/gems/3.1.0' , execute `gem env` for more information

To install the version of bundler this project requires, run `gem install bundler -v '< 2'`
```

In my Gemfile or Gemfile.lock there's no bundler < 2 specification... it's frustrating.

I tried to force binstubs with `bundle binstubs bundler --force` (must be forced at every deploy!) and after that I get this error:

```
$ bin/vite
/usr/share/rvm/rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/requirement.rb:106:in `parse': Illformed requirement [""] (Gem::Requirement::BadRequirementError)
	from /usr/share/rvm/rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/requirement.rb:138:in `block in initialize'
	from /usr/share/rvm/rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/requirement.rb:138:in `map!'
	from /usr/share/rvm/rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/requirement.rb:138:in `initialize'
	from /home/rails/my-project/releases/20230324161244/bin/bundle:97:in `new'
	from /home/rails/my-project/releases/20230324161244/bin/bundle:97:in `activate_bundler'
	from /home/rails/my-project/releases/20230324161244/bin/bundle:86:in `load_bundler!'
	from /home/rails/my-project/releases/20230324161244/bin/bundle:110:in `<top (required)>'
	from bin/vite:19:in `load'
	from bin/vite:19:in `<main>'
```

This is the output of

```
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.3.7
  - RUBY VERSION: 3.1.1 (2022-02-18 patchlevel 18) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/share/rvm/gems/ruby-3.1.1
  - USER INSTALLATION DIRECTORY: /home/rails/.local/share/gem/ruby/3.1.0
  - RUBY EXECUTABLE: /usr/share/rvm/rubies/ruby-3.1.1/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /usr/share/rvm/gems/ruby-3.1.1/bin
  - SPEC CACHE DIRECTORY: /home/rails/.local/share/gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-linux
  - GEM PATHS:
     - /usr/share/rvm/gems/ruby-3.1.1
     - /usr/share/rvm/rubies/ruby-3.1.1/lib/ruby/gems/3.1.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/share/rvm/gems/ruby-3.1.1/bin
     - /usr/share/rvm/gems/ruby-3.1.1@global/bin
     - /usr/share/rvm/rubies/ruby-3.1.1/bin
     - /usr/share/rvm/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games
     - /snap/bin
```

I have these bundler versions:

```
$ gem list | grep bundle
bundler (default: 2.3.7, 2.2.11)
bundler-unload (1.0.2)
rubygems-bundler (1.4.5)
```

This is what I tried to do:

- [x] I remove BUNDLED_WITH from Gemfile.lock with no luck
- [x] vite command works great on development.. not in production
- [x] I have tried upgrading by running `bundle update vite_ruby`.
- [x] I have read the __[troubleshooting section]__ before opening an issue.

**Comment by ElMassimo** [comment]
Hi Mattia!

Since Vite Ruby relies on Bundler to generate the binstub, and I haven't seen this problem before, it's likely that your application has another gem with an invalid requirement, causing bundler to fail when using a binstub.

Try running `bundle exec vite` instead.

If you provide a minimal reproduction, I can take a look.

**Comment by omsoft** [comment]
Somehow I managed to resolve by downgrading Vite ( I was already using bundler ).
