### ISSUE TITLE
issue with dry-cli 0.7

### ISSUE THREAD

**Issue by adenta** [ElMassimo/vite_ruby#76]
Last week I did a clean install of the vite_rails gem.

Just tried to do one now, and it didn't work.

This was resolved by going into my `Gemfile.lock` and downgrading `dry-cli` to version 0.6.

**Comment by braidn** [comment]
Confirmed! I have the same issue. Stacktrace using Ruby 2.7.1 and Dry CLI 0.7:

```shell
bundler: failed to load command: vite (/Users/braidn/src/play/ruby/ror6-explore/.bundle/ruby/2.7.0/bin/vite)
LoadError: cannot load such file -- dry/cli/utils/files
.bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
.bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
.bundle/ruby/2.7.0/gems/vite_ruby-1.2.9/lib/vite_ruby/cli/install.rb:3:in `<top (required)>'
  .bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'
  .bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'
  .bundle/ruby/2.7.0/gems/vite_ruby-1.2.9/lib/vite_ruby/cli.rb:13:in `<class:CLI>'
 .bundle/ruby/2.7.0/gems/vite_ruby-1.2.9/lib/vite_ruby/cli.rb:7:in `<top (required)>'
.bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'
 .bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'
  .bundle/ruby/2.7.0/gems/vite_ruby-1.2.9/exe/vite:9:in `<top (required)>'
 .bundle/ruby/2.7.0/bin/vite:23:in `load'
 .bundle/ruby/2.7.0/bin/vite:23:in `<top (required)>'
```

**Comment by ElMassimo** [comment]
Thanks for reporting. It's unfortunate that they released a minor version with this breaking change.

The missing file seems to have been extracted to a new gem, dry-files.

I will release a new version with updated dependencies, and make sure to be more strict with the version of dry-cli to prevent a similar issue in the future.
